### ISSUE TITLE
license

### ISSUE THREAD

**Issue by dvolgyes** [zsyOAOA/noise_est_ICCV2015#1]
Would you mind adding an explicit license?
It would make it easier to reuse.
See e.g. Scipy/Numpy/Pytorch use 3 clause BSD variants,
but there are plenty of options: MIT, (A)GPL, Apache, MPL, public domain, etc.

**Comment by zsyOAOA** [comment]
Thanks for you suggestion. I had added a license.

**Comment by dvolgyes** [comment]
Thank you for publishing your work.
